FROM devbeta/glassfish:5.1.0-correttojdk-8.222.10.1


LABEL name="GlassFishA"
LABEL nodeType="ash-glassfish"
LABEL nodeTypeAlias=""
LABEL cluster="https://raw.githubusercontent.com/annajel/glassfish/master/5.1.0-correttojdk-8.222.10.1/cluster.json" 
