FROM devbeta/glassfish:5.1.0-adoptopenjdk-8.0_222

LABEL name="GlassFishOS"
LABEL nodeType="glassfish-os"
LABEL nodeTypeAlias=""
LABEL cluster="https://raw.githubusercontent.com/mrAlexZT/glassfish/master/5.1.0-adoptopenjdk-8.0_222/cluster.json" 
