FROM devbeta/glassfish:5.0-openjdk-1.8.0_144

LABEL name="ash+GlassFish"
LABEL nodeType="ash-glassfish"
LABEL nodeTypeAlias=""
LABEL cluster="https://raw.githubusercontent.com/annajel/glassfish/master/cluster.json" 
