FROM devbeta/glassfish:5.1.0-openjdk-1.8.0_222

LABEL name="GlassFishA"
LABEL nodeType="ash-glassfish"
LABEL nodeTypeAlias=""
LABEL cluster="https://raw.githubusercontent.com/annajel/glassfish/master/5.1.0-openjdk-1.8.0_222/cluster.json" 
